import countries from "@/data/countries.json";

/** `{ GLOBAL: "Worldwide", CC: "Name" }` — regenerated by the catalog scripts from date-holidays. */
export const COUNTRY_NAMES: Record<string, string> = countries as Record<string, string>;

export function regionLabel(code: string): string {
  if (code === "GLOBAL") return "Worldwide";
  return COUNTRY_NAMES[code] || code;
}

export function regionSummary(regions: string[], limit = 3): string {
  if (regions.includes("GLOBAL") && regions.length === 1) return "Worldwide";
  if (regions.length > 12) return `${regions.length} countries`;
  const names = regions.filter((r) => r !== "GLOBAL").map(regionLabel);
  if (names.length === 0) return "Worldwide";
  if (names.length <= limit) return names.join(" · ");
  return `${names.slice(0, limit).join(" · ")} +${names.length - limit}`;
}

/**
 * ISO codes whose English name contains `q` (case-insensitive). Lets a search for
 * "France" match rows tagged FR only. Empty for queries shorter than 3 characters.
 */
export function regionCodesMatching(q: string): string[] {
  const needle = q.trim().toLowerCase();
  if (needle.length < 3) return [];
  const out: string[] = [];
  for (const [code, name] of Object.entries(COUNTRY_NAMES)) {
    if (code === "GLOBAL") continue;
    if (name.toLowerCase().includes(needle)) out.push(code);
  }
  return out;
}
