do $$
begin
  if (select count(*) from public.series where recurrence->>'kind'='external' and recurrence->>'source'='astronomy') <> 12 then
    raise exception 'astronomy series FK targets or external-provider metadata missing';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-drift'
      and source='astronomy' and source_key='astronomy:season:2026:sep-equinox'
      and slug='september-equinox-2026-09-23' and date='2026-09-23T00:05:39Z'
      and date_precision='instant' and not all_day and timezone='UTC') then
    raise exception 'fixed September 22 proxy did not become the correct September 23 instant while retaining its ID';
  end if;
  if not exists(select 1 from public.event_slugs where slug='september-equinox-2026-09-22' and event_id='verify-astro-drift') then
    raise exception 'corrected proxy lost its old permalink';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-duplicate' and not published and status='retired' and not featured and not indexable) then
    raise exception 'a distinct autogenerated duplicate is still public';
  end if;
  if not exists(select 1 from public.event_slugs where slug='northern-hemisphere-summer-solstice-2027-06-21' and event_id='verify-astro-computed') then
    raise exception 'duplicate URL does not redirect to the existing computed event';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-computed'
      and series_slug='northern-hemisphere-summer-solstice' and featured) then
    raise exception 'computed event did not retain the established series and featured prominence';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-merged'
      and source='astronomy' and source_key='astronomy:season:2027:sep-equinox'
      and date_precision='instant' and not all_day and confidence=0.95) then
    raise exception 'same-day provenance hash suppressed the ownership/precision correction';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-reviewed'
      and source='curated' and date_precision='day' and source_url='https://example.com/independently-reviewed-date') then
    raise exception 'an independently sourced curated occurrence was changed';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-hidden' and source='curated' and not published) then
    raise exception 'a deliberately unpublished event was changed';
  end if;
  if not exists(select 1 from public.events where id='verify-astro-cancelled' and source='curated' and status='cancelled') then
    raise exception 'a deliberately cancelled event was changed';
  end if;
  if (select count(*) from public.events) <> 7 then
    raise exception 'astronomy migration unexpectedly seeded unrelated catalog events';
  end if;
  raise notice 'Astronomy correction checks passed (ownership, exact instant, immutable ID, aliases, duplicate retirement, series, reviewed-source preservation).';
end $$;

-- These temporary fixtures must not affect the independent upcoming catalog test.
delete from public.events where id like 'verify-astro-%';
